# starting point application.yml 파일

spring:
  profiles:
    active: dev

# 추후 jar실행시
# 아래와 같이 실행시 application.yml에 설정을 덮어쓰기
# java "-Dspring.profiles.active=prod" -jar <jar파일명>



#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/newboard
#    username: root
#    password: 1234
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#logging:
#  level:
##    로그레벨 : trace < debug < info < error 순서의 로그레벨을 가짐
##    즉 info로 설정시 trace와 debug로그는 줄력되지 않음.
#    root: info
#  file:
#    name: logs/app.log